version: '3.4'
services:
  database:
    image: mongo    
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data
    restart: always
  backend:
    image: backend
    build: ./backend       
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://database/react-app  
    restart: always
    depends_on:
      - database
    
    