version: '3.4'

services:
  backend:
    image: demo5
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      TOKEN: ${TOKEN}
    ports:
      - 4000:5000

