version: '3.4'

services:
  nodeserver:
    image: nodeserver
    build:
      context: demo3
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
